export enum JoyrideClassNames {
    METRIC_CARD = 'JOYRIDE-METRIC-CARD',
    METRIC_CARD_TITLE = 'JOYRIDE-METRIC-CARD-TITLE',
    METRIC_CARD_UPCOMING = 'JOYRIDE-METRIC-CARD-UPCOMING',
    METRIC_CARD_DATA_SOURCES = 'JOYRIDE-METRIC-CARD-DATA-SOURCES',
    DASHBOARD_ACTIONABLES = 'JOYRIDE-DASHBOARD-ACTIONABLES',
}